### ISSUE TITLE
Uncaught (in promise) TypeError: filePatchItem.getRealItemPromise is not a function

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1451]
1. Open any file
1. Right click and pick `View staged/unstaged changes`

```
Uncaught (in promise) TypeError: filePatchItem.getRealItemPromise is not a function
    at RootController.viewChangesForCurrentFile (C:/Users/lineri/.atom/packages/github/lib/controllers/root-controller.js:532:27)
    at <anonymous>
```

Atom 1.28.0-dev-a3631f0da
GitHub@https://github.com/atom/github/commit/2d229668ea91f505fc3939d9a1ed48de7e89935b

**Comment by smashwilson** [comment]
It looks like this was introduced in #1390, so it needs to be backported to:

- [ ] 0.16-releases
- [ ] 0.15-releases
- [ ] 0.14-releases
